install.packages("pacman")
install.packages("remotes")
remotes::install_github("nickmckay/lipdR",ref = "neotoma2lipd")
remotes::install_github("nickmckay/geoChronR")
remotes::install_github("NeotomaDB/neotoma2")
remotes::install_github("LinkedEarth/actR")
